# Generated by Django 4.2.3 on 2023-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.IntegerField(
                choices=[(0, "user"), (1, "admin")], default=0
            ),
        ),
    ]
