# Generated by Django 4.2.3 on 2023-09-15 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
