# Generated by Django 4.2.3 on 2023-09-18 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_customuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="person_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="person_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="person_surname",
            new_name="surname",
        ),
    ]
