version: "3.9"

services:
  frontend:
      container_name: frontend
#      volumes:
#        - static:/home/medsite/app/public/static
      environment:
        - REACT_APP_BASE_API_URL=${REACT_APP_BASE_API_URL}
        - REACT_APP_PUBLIC_URL=${REACT_APP_PUBLIC_URL}
      ports:
        - 3000:80
      build:
        context: ./FrontEnd
        target: production
      networks:
        - medsite_network

networks:
  medsite_network:
