name: EsLint

on: [push, pull_request]
   branches:
     - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/eslint-action@1.0.2
        with:
          files: FrontEnd/