name: Testing BE
on: pull_request

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-verion: 3.10
      - name: install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r medsite/requirements.txt
      - name: running tests
        run: python medsite/manage.py test
